language: cpp
addons:
  apt:
    packages:
      - liblapack-dev
script:
  - mkdir cmake-build-release
  - cd cmake-build-release
  - cmake -DCMAKE_BUILD_TYPE=Release -DESPECIA_PURE_CMAES_VERSION=$YEAR ..
  - make -j clean all util $TEST
matrix:
  include:
    - os: osx
      env:
        - TEST="unittests"
        - YEAR=2014
    - os: osx
      env:
        - TEST="unittests"
        - YEAR=2004
    - os: osx
      env:
        - TEST="sanitytests"
        - YEAR=2014
    - os: osx
      env:
        - TEST="stresstests"
        - YEAR=2014
    - os: linux
      env:
        - TEST="unittests"
        - YEAR=2014
      dist: trusty
      sudo: required
    - os: linux
      env:
        - TEST="sanitytests"
        - YEAR=2014
      dist: trusty
      sudo: required
