language: cpp
addons:
  apt:
    packages:
      - liblapack-dev
script:
  - mkdir cmake-build-release
  - cd cmake-build-release
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j clean all util
  - make "$TEST"
matrix:
  include:
    - os: osx
      env:
        - TEST="unittests"
    - os: osx
      env:
        - TEST="test1"
    - os: osx
      env:
        - TEST="test2"
    - os: osx
      env:
        - TEST="test3"
    - os: osx
      env:
        - TEST="test4"
    - os: linux
      env:
        - TEST="unittests"
      dist: trusty
      sudo: required
    - os: linux
      env:
        - TEST="test1"
      dist: trusty
      sudo: required
    - os: linux
      env:
        - TEST="test2"
      dist: trusty
      sudo: required
    - os: linux
      env:
        - TEST="test3"
      dist: trusty
      sudo: required
    - os: linux
      env:
        - TEST="test4"
      dist: trusty
      sudo: required
