language: cpp
addons:
  apt:
    packages:
      - liblapack-dev
script:
  - mkdir cmake-build-release
  - cd cmake-build-release
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j "$TASK"
matrix:
  include:
    - os: osx
      env:
        - TASK="clean unittests"
    - os: osx
      env:
        - TASK="clean all util test1"
    - os: osx
      env:
        - TASK="clean all util test2"
    - os: osx
      env:
        - TASK="clean all util test3"
    - os: osx
      env:
        - TASK="clean all util test4"
    - os: linux
      env:
        - TASK="clean unittests"
      dist: trusty
      sudo: required
    - os: linux
      env:
        - TASK="clean all util test1"
      dist: trusty
      sudo: required
    - os: linux
      env:
        - TASK="clean all util test2"
      dist: trusty
      sudo: required
    - os: linux
      env:
        - TASK="clean all util test3"
      dist: trusty
      sudo: required
    - os: linux
      env:
        - TASK="clean all util test4"
      dist: trusty
      sudo: required
