language: cpp
addons:
  apt:
    packages:
      - liblapack-dev
script:
  - mkdir cmake-build-release
  - cd cmake-build-release
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j clean all util
  - ctest --verbose --tests-regex "$TEST"
matrix:
  include:
    - os: osx
      env:
        - TEST="especid_test"
    - os: osx
      env:
        - TEST="especiv_test"
    - os: osx
      env:
        - TEST="especix_test"
    - os: osx
      env:
        - TEST="especia_test"
    - os: linux
      env:
        - TEST="especid_test"
      dist: trusty
      sudo: required
    - os: linux
      env:
        - TEST="especiv_test"
      dist: trusty
      sudo: required
    - os: linux
      env:
        - TEST="especix_test"
      dist: trusty
      sudo: required
    - os: linux
      env:
        - TEST="especia_test"
      dist: trusty
      sudo: required
