language: cpp
addons:
  apt:
    packages:
      - liblapack-dev
script:
  - mkdir cmake-build-release
  - cd cmake-build-release
  - cmake -DCMAKE_BUILD_TYPE=Release -DESPECIA_PURE_CMAES_VERSION="$PURE_CMAES_VERSION" ..
  - make -j clean all util
  - make "$TEST"
matrix:
  include:
    - os: osx
      env:
        - TEST="unittests"
        - PURE_CMAES_VERSION="2014"
    - os: osx
      env:
        - TEST="unittests"
        - PURE_CMAES_VERSION="2004"
    - os: osx
      env:
        - TEST="integrationtests"
        - PURE_CMAES_VERSION="2014"
    - os: osx
      env:
        - TEST="systemtests"
        - PURE_CMAES_VERSION="2014"
    - os: linux
      env:
        - TEST="unittests"
        - PURE_CMAES_VERSION="2014"
      dist: trusty
      sudo: required
    - os: linux
      env:
        - TEST="integrationtests"
        - PURE_CMAES_VERSION="2014"
      dist: trusty
      sudo: required
