language: cpp
addons:
  homebrew:
    packages:
      - gcovr
    update: false
  apt:
    packages:
      - gcovr
      - intel-mkl
script:
  - mkdir cmake-build-release
  - cd cmake-build-release
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j clean all util $TEST
matrix:
  include:
    - os: osx
      env:
        - TEST="unittests"
      osx_image: xcode12.2
    - os: osx
      env:
        - TEST="integrationtests"
      osx_image: xcode12.2
    - os: linux
      env:
        - TEST="unittests"
      dist: focal
      sudo: required
    - os: linux
      env:
        - TEST="integrationtests"
      dist: focal
      sudo: required
after_success: 
  - bash <(curl -s https://codecov.io/bash)
  
