language: cpp
addons:
  apt:
    packages:
      - liblapack-dev
script:
  - mkdir cmake-build-release
  - cd cmake-build-release
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j clean all util $TEST
matrix:
  include:
    - os: osx
      osx_image: xcode9
      env:
        - TEST="unittests"
    - os: osx
      osx_image: xcode9
      env:
        - TEST="sanitytests"
    - os: osx
      osx_image: xcode9
      env:
        - TEST="stresstests"
    - os: linux
      env:
        - TEST="unittests"
      dist: trusty
      sudo: required
    - os: linux
      env:
        - TEST="sanitytests"
      dist: trusty
      sudo: required
