language: cpp
addons:
  apt:
    packages:
      - liblapack-dev
script:
  - mkdir cmake-build-release
  - cd cmake-build-release
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j clean all util $TEST
matrix:
  include:
    - os: osx
      env:
        - TEST="unittests"
    - os: osx
      env:
        - TEST="integrationtests"
    - os: linux
      env:
        - TEST="unittests"
      dist: bionic
      sudo: required
    - os: linux
      env:
        - TEST="integrationtests"
      dist: bionic
      sudo: required
