#!/usr/bin/env sh
## @file update-copyright
## Updates copyright notices
## @author Ralf Quast
## @date 2021
## @copyright MIT License
## @remark usage: update-copyright [file]...
set -e

if [ $# -lt 1 ]; then
    echo "usage: $0 [file]..."
    exit 1
fi

for filename in "$@"
do
    sed -f "@CMAKE_BINARY_DIR@"/update-copyright.sed -i .backup "${filename}"
done

for filename in "$@"
do
    rm -f "${filename}".backup
done
