#!/usr/bin/env sh
## @file erun
## Runs an Especia result HTML and searches for expected values, if specified
## @author Ralf Quast
## @date 2021
## @copyright MIT License
## @remark usage: erun {resultFile} {targetFile} [value]...
set -e

if [ $# -lt 2 ]; then
    echo "usage: $0 {resultFile} {targetFile} [value]..."
    exit 1
fi

resultFile="$1"
targetFile="$2"

ecom=$(dirname "$0")/ecom
emod=$(dirname "$0")/emod
elog=$(dirname "$0")/elog
# shellcheck disable=SC2094
# shellcheck disable=SC2091
${emod} < "${resultFile}" | $(${ecom} < "${resultFile}") | tee "${targetFile}" | ${elog}

shift
shift
for value in "${@}"
do
    grep --quiet --fixed-strings "<td><strong>${value}</strong></td>" "${targetFile}"
done
