#!/usr/bin/env sh
# Runs an Especia result HTML and searches for expected values, if specified
# Copyright (c) 2021 Ralf Quast
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# usage: erun {resultFile} {targetFile} [value]...
set -e

if [ $# -lt 2 ]; then
    echo "usage: $0 {resultFile} {targetFile} [value]..."
    exit 1
fi

resultFile="$1"
targetFile="$2"

ecom=$(dirname "$0")/ecom
emod=$(dirname "$0")/emod
elog=$(dirname "$0")/elog
# shellcheck disable=SC2094
# shellcheck disable=SC2091
${emod} < "${resultFile}" | $(${ecom} < "${resultFile}") | tee "${targetFile}" | ${elog}

shift
shift
for value in "${@}"
do
    grep --quiet --fixed-strings "<td><strong>""${value}""</strong></td>" "${targetFile}"
done
