#!/usr/bin/env sh
## @file foreach
## Applies a given command to each file supplied as argument.
## @author Ralf Quast
## @date 2021
## @copyright MIT License
## @attention usage: foreach {command} [file]...
set -e

if [ $# -lt 1 ]; then
    echo "usage: $0 {command} [file]..."
    exit 1
fi

command="${1}"

shift
for sourceFile in "${@}"
do
    cp "${sourceFile}" "${sourceFile}.backup"
    targetFile="$(basename "$sourceFile")"
    ${command} "${sourceFile}" "${targetFile}"
    mv "${targetFile}" "${sourceFile}"
done

for sourceFile in "${@}"
do
    rm -f "${sourceFile}.backup"
done
