#!/usr/bin/env bash
## @file foreach
## Applies a given command to each file supplied as argument.
## @author Ralf Quast
## @date 2021
## @copyright MIT License
## @attention usage: foreach {command} [file]...
set -e

if [ $# -lt 1 ]; then
    echo "usage: $0 {command} [file]..."
    exit 1
fi

command="${1}"

for sourceFile in "${@:2}"; do
    targetFile="$(basename "$sourceFile").new"
    ${command} "${sourceFile}" "${targetFile}"
    mv "${targetFile}" "${sourceFile}"
done
